apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instanceserviceexposures.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: InstanceServiceExposure
    plural: instanceserviceexposures
    singular: instanceserviceexposure
    shortNames:
      - ise
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instanceRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                      targetPort:
                        type: integer
            status:
              type: object
              properties:
                externalIP:
                  type: string
                assignedPorts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                      targetPort:
                        type: integer
                      assignedPort:
                        type: integer
      subresources:
        status: {}