{{- $pe := .Values.configurations.publicExposure -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pe.addressPool }}
  namespace: metallb-system
spec:
  addresses:
  {{- range $pe.ipPool }}
  - {{ . | quote }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ printf "%s-adv" $pe.addressPool }}
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ $pe.addressPool }}