apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: netshoot-test1
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: netshoot
    namespace: workspace-standalone
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe
  publicExposure:
    servicesportmappings:
      - name: ssh
        port: 0 # TODO cambiare in publicPort 
        targetPort: 22
      - name: http
        port: 30005
        targetPort: 80
      - name: https
        port: 0
        targetPort: 443