apiVersion: crownlabs.polito.it/v1alpha2
kind: Template
metadata:
  name: netshoot
  namespace: workspace-standalone
spec:
  prettyName: Netshoot
  description: A container with a collection of networking tools for troubleshooting and debugging
  environmentList:
    - name: netshoot-environment
      mountMyDriveVolume: false
      environmentType: Standalone
      mode: Standard
      image: nicolaka/netshoot:latest
      containerStartupOptions:
        contentPath: /root
      resources:
        cpu: 1
        memory: 512Mi
        reservedCPUPercentage: 25
  workspace.crownlabs.polito.it/WorkspaceRef:
    name: standalone
  deleteAfter: 7d