# Default values for instance-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configurations:
  generic:
    whitelistLabels: crownlabs.polito.it/operator-selector=production
    websiteBaseUrl: crownlabs.example.com
    instancesAuthUrl: https://crownlabs.example.com/auth
  containerEnvironmentOptions:
    tag: ""
    websockifyImage: crownlabs/websockify
    xVncImage: crownlabs/tigervnc
    contentDownloaderImage: crownlabs/content-downloader
    contentUploaderImage: crownlabs/content-uploader
    instmetricsServerEndpoint: crownlabs-instmetrics.crownlabs-production:9090
  containerVmSnapshots:
    kanikoImage: gcr.io/kaniko-project/executor:latest
    exportImage: "crownlabs/img-exporter"
    exportImageTag: ""
  privateContainerRegistry:
    url: registry.crownlabs.example.com
    secretName: registry-credentials
  maxConcurrentReconciles: 1
  automation:
    maxConcurrentTerminationReconciles: 1
    terminationStatusCheckTimeout: "3s"
    terminationStatusCheckInterval: "2m"
    maxConcurrentSubmissionReconciles: 1
  sharedVolumeOptions:
    storageClass: rook-nfs
  publicExposure:
    # The IP pool used to assign public IPs to instances.
    # for Metallb, specify IPs in format /<subnet-mask> or as a range, not single IP.
    ipPool:
      - 172.18.0.240-172.18.0.249
      - 172.18.0.250/30
    annotationKeys:
      - "metallb.universe.tf/shared-ip"
      - "metallb.universe.tf/loadBalancerIPs"
      

image:
  repository: crownlabs/instance-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations:
  reloader.stakater.com/auto: "true"
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 20000
  runAsGroup: 20000
  privileged: false

resources:
  limits:
    memory: 750Mi
    cpu: 1000m
  requests:
    memory: 250Mi
    cpu: 100m

rbacResourcesName: crownlabs-instance-operator
